# Site settings
title: Stage
subtitle: MATLAB-based visual stimulus system
email: stage-vss@googlegroups.com
url: http://stage-vss.github.io
description: "Stage is a flexible and extensible MATLAB-based visual stimulus system."
download: https://github.com/Stage-VSS/stage2/releases/download/2.0.1.1/Stage.mltbx
version: Version 2.0.1.1 (2.0-b1)
github: https://github.com/Stage-VSS/stage2

# Collections
collections:
- features

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9C27B0
  primary-rgb: "100,73,94"
  secondary: 7B1FA2
  accent: B388FF

# Footer settings
footer:
  copyright: Stage-VSS

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google
    url: https://groups.google.com/forum/#!forum/stage-vss
  - title: github
    url: https://github.com/Stage-VSS/stage2

# Build settings
markdown: kramdown
permalink: pretty
