# Permalinks
#
permalink:           pretty

# Setup
title:               Stage
tagline:             'MATLAB-based visual stimulus system'
description:         'A MATLAB-based visual stimulus system for vision research.'
url:                 http://stage-vss.github.io
baseurl:             ''

# About/contact
author:
  name:              Stage-VSS
  url:               http://stage-vss.github.io
  email:             symphony-das@googlegroups.com

# Custom vars
version:             2.0.1.4

github:
  repo:              https://github.com/Stage-VSS/stage2
