# Permalinks
permalink:           pretty

# Setup
title:               Stage
tagline:             'Visual Stimulus System'
description:         'Stage is a MATLAB based visual stimulus system for vision research.'
url:                 http://stage-vss.github.io
baseurl:             ''
usergroup:           https://groups.google.com/forum/#!forum/symphony-das

# About/contact
author:
  name:              Stage-VSS
  url:               http://stage-vss.github.io
  email:             symphony-das@googlegroups.com

# Collections
collections:
  stimuli:
    output: true
  effects:
    output: true

# Custom vars
version:             2.2.3.0

github:
  repo:              https://github.com/Stage-VSS/stage
  org:               https://github.com/Stage-VSS

gitbook:
  book:              https://cafarm.gitbooks.io/stage
