# Permalinks
permalink:           pretty

# Setup
title:               Stage
tagline:             'Visual Stimulus System'
description:         'Stage is a MATLAB based visual stimulus system for vision research.'
url:                 http://stage-vss.github.io
baseurl:             ''

# About/contact
author:
  name:              Stage-VSS
  url:               http://stage-vss.github.io
  email:             symphony-das@googlegroups.com

# Collections
collections:
- stimuli
- effects

# Custom vars
version:             2.0.3.3

github:
  repo:              https://github.com/Stage-VSS/stage

gitbook:
  book:              https://cafarm.gitbooks.io/stage
